version: 2

multi-ecosystem-groups:
  all-dependencies:
    schedule:
      interval: weekly
      day: monday
      timezone: Europe/London
    open-pull-requests-limit: 10
    reviewers:
      - Ensono/dependency-management

updates:
  - package-ecosystem: pip
    directory: "/fabric_content"
    multi-ecosystem-group: all-dependencies

  - package-ecosystem: terraform
    directory: "/deploy/terraform/infra"
    multi-ecosystem-group: all-dependencies

  - package-ecosystem: terraform
    directory: "/deploy/terraform/infra/modules/ensono-stacks-foundation-azure"
    multi-ecosystem-group: all-dependencies

  - package-ecosystem: terraform
    directory: "/fabric_content/data_engineering/example_copy_pipeline/terraform"
    multi-ecosystem-group: all-dependencies

  - package-ecosystem: terraform
    directory: "/fabric_content/data_engineering/example_spark_pipeline/terraform"
    multi-ecosystem-group: all-dependencies

  - package-ecosystem: github-actions
    directory: "/"
    multi-ecosystem-group: all-dependencies
