import:
  - ./build/eirctl/contexts.yml
  - ./build/eirctl/tasks.yml

pipelines:
  docs:
    - task: build:number
    - task: _docs
      depends_on:
        - build:number

  lint:
    - task: lint:yaml
    - task: lint:terraform:format
