# Pipeline files
pipeline:
  - type: azdo
    files:
      - name: build
        path: build/ado/pipeline.yml
      - name: variable
        path: build/ado/variables.yml
    items:
      - build/ado/*.yaml
    replacements:
      - pattern: ^\svalue:\sensono$
        value: {{ .Inputs.Business.Company }}

  - type: gha

setup:
  operations:
    - action: copy
