[#permissions]
=== Permissions

There are a number of permissions that need to be applied to Fabric in order for people to be able to access it.

IMPORTANT: Not all of the permissions are defined in the same way, for example some require the UPN of the user and others need the object ID.

To make this is as simple as possible, a comma delimited string of definitions need to be supplied. The format of this string is as follows:

```
<upn>:<capacity_admin>:<guid>:<workspace_permission>
```

This is required because the permissions for capacity admins and workspace members are defined differently. The following table shows examples of the different formats for users or service principals.

[cols="1,3", options="header"]
|===
| Type | String
.2+| User | `fred.bloggs@example.com:false:e9084ea1-de42-403f-ae10-8ea566c10313:Contributor`
| This will assign the use Fred Bloggs as a Contributor to the workspaces. The GUID is used when assigned in the workspace
The user does not have capacity admin permissions
.2+| Service Principal | `:true:f8dda1ce-4a18-461e-b0e6-b11aca05e6d4:Member`
| Here the GUID of the Service Principal is only required as it is used for both setting as a capacity admin and a workspace member.
Service Principals are specified using their GUID and not by name hence why the first field is empty.
|===

NOTE: The GUID for a User _can_ be read by Terraform, however the Service Principal requires read only access to the Entra ID directory to do this. Please refer to <<get_id_of_ad_user>> for more information.

The Service Principal that is used to deploy these resources using Terraform will automatically be given Capacity admin rights.
